import './globals.css';
import type { Metadata } from 'next';
import Header from '@/components/organisms/header';
import Footer from '@/components/organisms/footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	keywords: ['Next.js', 'React', 'JavaScript'],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
