import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio gashi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-full">
          <div className="flex h-screen items-center justify-center mx-auto my-0 w-4/5 max-w-[1000px]">
            GASHI portfolio
          </div>
        </div>
      </main>
    </>
  );
}
